FROM apache/airflow:2.8.3-python3.11

RUN pip install uv
USER airflow

RUN pip install kafka-python==2.0.2 psycopg2-binary==2.9.10 pandas==2.2.2 requests==2.31.0 python-dotenv==1.0.0

WORKDIR /opt/airflow
